apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - iscsi_pv_00.yml
  - iscsi_pv_01.yml
  - iscsi_pv_02.yml
  - iscsi_pv_03.yml
  - iscsi_pv_04.yml
  - iscsi_pv_05.yml
  - iscsi_pv_06.yml
  - iscsi_pv_07.yml
  - iscsi_pv_08.yml

